### ISSUE TITLE
Baker Heart and Diabetes Institute

### ISSUE THREAD

**Issue by DavidMc1948** [thecapitalistcycle/setup#3]
"The" is not included in its name. Just an informal addition.

It has about a dozen business names including Baker Institute  and Baker Heart Research Institute

It is an Australian Public Company
"A company is a non-individual client type. Company is defined to include a body corporate and any other unincorporated association or body of persons but does not include a partnership or a non-entity joint venture."

It is registered with the Australian Charities and not-for-profits Commission (ACNC)

**Comment by dentarthur** [comment]
Transferred to https://github.com/Maksakovsky-admin/technical/issues/2

Closing both #3 and #4 here.
