### ISSUE TITLE
South Asian Public Affairs Council

### ISSUE THREAD

**Issue by DavidMc1948** [thecapitalistcycle/setup#4]
South Asian Public Affairs Council Inc is a an incorporated association but "Inc." or "Incorporated" is not apparent on its website.

I'll check out a few more examples tomorrow.

**Comment by dentarthur** [comment]
Thanks. That is probably enough. Lets use your separate issues tracker for
administrative and technical details like this from now on:

https://github.com/Maksakovsky-admin/technical/issues

Several others not interested in details should get all notices consulting
re setup plans here. eg Will propose names and aims for incorporated
association here for other members, but not background details.
