### ISSUE TITLE
Four chapters of DITA

### ISSUE THREAD

**Issue by PetervGreen** [thecapitalistcycle/setup#7]
[_----_(Chapter_3_How_DITA_Evolved_into_LwDITA).pdf](https://github.com/thecapitalistcycle/setup/files/2867037/_----_.Chapter_3_How_DITA_Evolved_into_LwDITA.pdf)
[_----_(Chapter_4_The_LwDITA_Initial_Authoring_Formats).pdf](https://github.com/thecapitalistcycle/setup/files/2867038/_----_.Chapter_4_The_LwDITA_Initial_Authoring_Formats.pdf)
[_----_(Chapter_5_The_LwDITA_Map_Components).pdf](https://github.com/thecapitalistcycle/setup/files/2867039/_----_.Chapter_5_The_LwDITA_Map_Components.pdf)
[_----_(Chapter_7_The_Abstractions_Behind_Intelligent_Content).pdf](https://github.com/thecapitalistcycle/setup/files/2867040/_----_.Chapter_7_The_Abstractions_Behind_Intelligent_Content.pdf)

**Comment by dentarthur** [comment]
PS Book may now by accessible to other students and staff at your
institution who could download remaining chapters?

**Comment by PetervGreen** [comment]
Arthur

Time to ask a favour from Paul Adams…

I will wait for a few days to see how current efforts pan out.

Peter

PS I will ask him to download the chapters and sections which we haven’t got.

> PS Book may now by accessible to other students and staff at your
> institution who could download remaining chapters?
>

**Comment by DavidMc1948** [comment]
Here are chapters 1 and 2. I was allowed to print to pdf 60 pages and those two chapters are 59 pages. 

When I opened the file it told me it had expired and to please close. I clicked OK and found myself with full access. It will be interesting to see how long that lasts.

I had to make a compressed copy so the image is not perfect

[Chapters 1&2](https://github.com/Maksakovsky-admin/technical/blob/master/Lightweight%20DITA%20-%20chaps1-2%20-readable%20-%20compressed.pdf)

**Comment by DavidMc1948** [comment]
Screen dumps of chapter 6 pages trimmed and combined using Nuance Power PDF
[Chapter 6.pdf](https://github.com/thecapitalistcycle/setup/files/2871650/Chapter.6.pdf)

Will now try and capture the rest of the book.

**Comment by PetervGreen** [comment]
Great!!!

It seems that their copy protection is hit and miss - they just hope people like me will believe them, when they say you can only read one chapter, for example. They give you more than they say they will - it’s the opposite of spam.

We only really need chapters 5 and 7.

**Comment by DavidMc1948** [comment]
We now have the entire book. I will upload the remaining screen dumps tomorrow as PDFs.

**Comment by PetervGreen** [comment]
Great!!!

It seems that their copy protection is hit and miss - they just hope people like me will believe them, when they say you can only read one chapter, for example. They give you more than they say they will - it’s the opposite of spam.

We only really need chapters 5 and 7.

We only really need chapters 6  and 8.

**Comment by DavidMc1948** [comment]
That's it. I'll stitch the whole book together shortly

[BeforeChap1.pdf](https://github.com/thecapitalistcycle/setup/files/2872598/BeforeChap1.pdf)

[Chapter 8.pdf](https://github.com/thecapitalistcycle/setup/files/2872601/Chapter.8.pdf)

[Conclusion&index.pdf](https://github.com/thecapitalistcycle/setup/files/2872603/Conclusion.index.pdf)

**Comment by dentarthur** [comment]
Great! Have downloaded and opened ok. All done!

I am ok with unassembled but assembly will be useful for others.

Better to use the preview available from publishers web site for front
matter plus ch1 pdf 1-52 of attached file. (The free preview may correspond
to the 60 pages print limit).

Remaining pages pdf 53 to 60 are reference lists for each chapter.

Collecting references together was necessary for the preview and handy
although not necessary to include in end matter of complete assembly. Be
good to add it as part of end matter.

BTW I did include a link to preview file earlier but am attaching it now.

**Comment by dentarthur** [comment]
[Creating_Creating_Intelligent_Content_with_Lightweight_9781351187510_preview.pdf](https://github.com/thecapitalistcycle/setup/files/2872612/Creating_Creating_Intelligent_Content_with_Lightweight_9781351187510_preview.pdf)

**Comment by DavidMc1948** [comment]
Shall add review stuff.

**Comment by dentarthur** [comment]
I have read the book and will write some notes soon.

Closing this issue as should be in bib team discussion:

https://github.com/orgs/thecapitalistcycle/teams/bib

When assembled Dave should put it there.

**Comment by PetervGreen** [comment]
Accounting for value in Marx's Capital : the invisible hand / Rob Bryer

Book has arrived - I will pick it up tomorrow…

**Comment by dentarthur** [comment]
Great! Download or hardcopy?

**Comment by PetervGreen** [comment]
Accounting for value in Marx's Capital : the invisible hand / Rob Bryer

I have the book. Do you want me to convert it into Russian?
